
helmController:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
sourceController:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
notificationController:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
kustomizeController:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
imageReflectionController:
  create: false
imageAutomationController:
  create: false