apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: flux-vpa
  namespace: vpa-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: helm-controller
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: helm-controller
      minAllowed:
        cpu: "100m"
        memory: "64Mi"
      maxAllowed:
        cpu: "500m"
        memory: "256Mi"
    - containerName: kustomize-controller
      minAllowed:
        cpu: "100m"
        memory: "64Mi"
      maxAllowed:
        cpu: "500m"
        memory: "256Mi"
    - containerName: source-controller
      minAllowed:
        cpu: "100m"
        memory: "64Mi"
      maxAllowed:
        cpu: "500m"
        memory: "256Mi"